characters = {
	{
		name = "Guy",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Guy.png')
	},
	{
		name = "Rascal",
		width = 48,
		height = 48,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 7,
		maxSpeedAir = 8,
		jumpForce = 18,
		gravity = 1,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Rascal.png')
	}
}