characters = {
	{
		name = "Guy",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Guy.png')
	},
	{
		name = "Lama",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .6,
		accelerationAir = .7,
		accelerationDuration = 1.1,
		frictionGround = .2,
		frictionAir = .1,
		frictionDuration = .3,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .39,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Lama.png')
	},
	{
		name = "Rascal",
		width = 48,
		height = 48,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 7,
		maxSpeedAir = 8,
		jumpForce = 18,
		gravity = 1,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Rascal.png')
	},
	{
		name = "Boot",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Boot.png')
	},
	{
		name = "Simon",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Simon.png')
	},
	{
		name = "Henry",
		width = 32,
		height = 48,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Henry.png')
	},
	{
		name = "Mary",
		width = 32,
		height = 32,
		squashX = 1.50,
		squashY = .75,
		stretchX = .50,
		stretchY = 1.25,
		restitution = 0.035,
		accelerationGround = .4,
		accelerationAir = .6,
		accelerationDuration = 1,
		frictionGround = .4,
		frictionAir = .2,
		frictionDuration = .2,
		maxSpeedGround = 8,
		maxSpeedAir = 10,
		jumpForce = 8,
		gravity = .4,
		maxGravity = 48,
		image = love.graphics.newImage('sprites/Mary.png')
	}
	
}